# Generated by Django 2.2.19 on 2023-04-26 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название ингредиента', max_length=50, verbose_name='Наименование ингредиента')),
                ('amount', models.IntegerField(help_text='Введите количество ингредиента', verbose_name='Количество')),
                ('measurement_unit', models.CharField(help_text='Введите единицу измерения', max_length=50, verbose_name='Единицы измерения')),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
            },
        ),
    ]
