# Generated by Django 2.2.19 on 2023-04-27 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20230427_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(help_text='Выберите ингредиенты из списка', related_name='ingredient_recipe', through='recipes.IngredientRecipe', to='ingredients.Ingredient', verbose_name='Ингредиенты'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(help_text='Выберите теги из списка', related_name='tag_recipe', through='recipes.TagRecipe', to='tags.Tag', verbose_name='Теги'),
        ),
    ]
