# Generated by Django 2.2.19 on 2023-04-27 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20230427_2137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientrecipe',
            options={'verbose_name': 'Ингредиент: Рецепт', 'verbose_name_plural': 'Ингредиенты: Рецепты'},
        ),
        migrations.AlterModelOptions(
            name='tagrecipe',
            options={'verbose_name': 'Тег: Рецепт', 'verbose_name_plural': 'Теги: Рецепты'},
        ),
    ]
